import turtle
t = turtle.Turtle()
turtle.bgcolor("white")
t.color("red")
t.width(2)
t.penup()
t.goto(0, -200)
t.pendown()
t.begin_fill()
t.fillcolor("red")
t.left(50)
t.forward(133)
t.circle(50, 200)
t.right(140)
t.circle(50, 200)
t.forward(133)
t.end_fill()
turtle.done()