import turtle

shin=turtle.Turtle()
turtle.bgcolor("white")
shin.color("red")
shin.width(2)
shin.penup()
shin.goto(0,-200)
shin.pendown()
shin.begin_fill()
shin.fillcolor("red")
shin.left(50)
shin.forward(133)
shin.circle(50,200)
shin.right(140)
shin.circle(50,200)
shin.forward(133)
shin.end_fill()
turtle.done()